### ISSUE TITLE
New magister.js version

### ISSUE THREAD

**Issue by lieuwex** [lesander/magister-calendar#10]
I don't know if this is automatically updated tbh, but magister.js has got 2 new critical updates today (the latest version is 1.8.3 now).

The old one couldn't login anymore and fullday appointments were broken.

Just wanted to let you know :smile:

**Comment by lesander** [comment]
Hey @lieuwex, thanks for the heads-up. In Magister Calendar's `package.json`, magister.js is defined as a dependency with version `1.8.x`, which means that NPM will automatically fetch the latest version within the _minor_ `8` (http://semver.org) (Also [see npm's docs](https://docs.npmjs.com/files/package.json#dependencies)). 

So unless you're pushing version `1.9.x`, this repo will be fine :smile:

**Comment by lieuwex** [comment]
great! :+1:

**Comment by lieuwex** [comment]
@lesander turns out I suck at coding, new critical version. It _is_ 1.9.0 now.

 https://github.com/simplyGits/MagisterJS/releases/tag/1.9.0
