### ISSUE TITLE
OngeldigeSessieStatus

### ISSUE THREAD

**Issue by ghost** [lesander/magister-calendar#12]
Ik krijg de foutmelding:

Could not login to magister. {"fouttype":"OngeldigeSessieStatus","omschrijving":null}

Wat kan ik hier tegen doen?

**Comment by lesander** [comment]
Hey Bruce, je krijgt deze foutmelding waarschijnlijk te zien omdat je Magister school een update heeft geïnstalleerd, waar je huidige geïnstalleerde MagisterJS nog niet mee overweg kan.

Waarschijnlijk heeft @lieuwex al een update uitgebracht voor MagisterJS. Zorg er voor dat je de laatste versie (**`1.14.2`**) hebt door `npm install magister.js --save` in je magister-calendar folder uit te voeren.

Als het goed is zou dat je probleem op moeten lossen. Als het niet lukt, of je nog vragen hebt hoor ik het graag!

**Comment by ghost** [comment]
Hey Sander,

Bedankt! Dit heeft het inderdaad opgelost.
Bedankt voor de snelle reactie!

Groet Bruce Martens

2015-12-09 16:30 GMT+01:00 notifications@github.com:

**Comment by ghost** [comment]
Hallo,

Nog een vraag. Ik heb crontab werkend dat zit helemaal goed.
Maar stel dat ik een vak verwijder handmatig in Google Calendar, hoe zorg
ik er dan dat hij weer terug komt? Want door gewoon de code te laten
draaien komt er geen verschil.

Groet bruce

**Comment by ghost** [comment]
Hallo,

Het is mij al gelukt.
Nogmaals bedankt voor uw geweldige code.

Groet Bruce.

2015-12-09 21:33 GMT+01:00 Bruce Martens bmartens2112@gmail.com:

**Comment by poespas** [comment]
Hallo, Ik krijg deze foutmelding ook. Dit is mijn log:

pi@raspberrypi:~/Bot/Magister-To-Google $ node magister-calendar.js
[_] 19:11:3 Magister Calendar v1.5.1 started.
System Time: 19:11:03
[_] 19:11:3 Using default period to fetch appointments for.
[_] 19:11:3 Determined period is:
From Thu Apr 21 2016 19:11:03 GMT+0000 (UTC)
To Fri Apr 22 2016 19:11:03 GMT+0000 (UTC).
[_] 19:11:3 Google OAuth2 token is valid.
[!] 19:11:4 Could not login to magister. {"fouttype":"OngeldigeSessieStatus","omschrijving":null}

**Comment by lesander** [comment]
Hey @wortel538, weet je zeker dat je de nieuwste Magister.js hebt? Zie mijn antwoord op Bruce hier boven. De nieuwste versie is op dit moment 1.18.0

**Comment by poespas** [comment]
Bedankt voor je snelle reactie, ik heb het vandaag geïnstalleerd, maar ik
ben niet de beste in node.js. ik had npm install magister.js gedaan en de
commando's hierboven. Het werkte daarna nogsteeds niet.

Groeten, Ik.

**Comment by lesander** [comment]
@wortel538 Vervelend, maar om het probleem op te kunnen lossen moeten we wat meer informatie hebben. 

Welke Magister versie heeft je school (kan je zien op jouwschool.magister.net), en welke versie zegt npm dat je hebt van Magister.js (zie output van 'npm list')?

**Comment by poespas** [comment]
Ik zal het morgen even uitzoeken, bedankt voor je hulp. :)

**Comment by ghost** [comment]
Beste,

Waarom zit ik in de CC?

Groet Bruce Martens
Op 20 apr. 2016 11:02 p.m. schreef <
notifications@github.com>:

**Comment by lieuwex** [comment]
@wortel538 Kan je misschien ook hier zetten wat https://JOUWSCHOOLHIER.magister.net/api/versie teruggeeft? Die geeft naast de versie van Magister ook nog verdere nuttige informatie :)

@brucemartens Omdat dit geplaatst was in de issue die je gemaakt hebt, dus stuurt github nu bij elk bericht je een e-mail. Als je dit niet wilt kan je links op 'unsubscribe' klikken

**Comment by poespas** [comment]
Hier zijn mijn versies:
http://pastebin.com/jbqeDtHi

Groeten. Ik.

**Comment by lieuwex** [comment]
De magister versie is prima, maar magister.js is nog op 1.11.0 in plaats van 1.19.0, je kan ook proberen in de folder waar magister-calendar staat `npm update` te doen. En dan kijken of magister.js wel op 1.19.0 is.

**Comment by lesander** [comment]
@wortel538, zoals je zelf misschien al hebt gezien gebruik je volgens npm Magister.js versie 1.11.0, in plaats van de nieuwste versie, 1.19.0. (edit: typo)

Update je dependencies (npm update, npm install magister.js --save) en check dan nog een keer je versies. Om je probleem op te lossen gaan we er van uit dat je zelf een beetje actief mee denkt aan wat je zou kunnen doen :) Ik hoor graag of het je lukt.

**Comment by poespas** [comment]
Ik had al wat geprobeerd, en "sudo npm update" of "sudo npm install
magister.js --save". Maar hij blijft op de oude versie staan, kan ik niet
een mapje downloaden en overzetten?

Groeten, Ik.

**Comment by lieuwex** [comment]
@wortel538 `rm -rf node_modules && npm install` valt ook nog te proberen

**Comment by poespas** [comment]
Nee, werkt niet. Ik zal nog even rondkijken op Google. Dank je wel voor je
hulp. ;)

Groeten. Ik.

**Comment by lesander** [comment]
@wortel538 Om meer hulp te kunnen geven zal je ons meer moeten vertellen dan 'werkt niet'. Wat werkt er niet? `rm -rf node_modules` zou gewoon moeten werken, desnoods met sudo er voor.

**Comment by poespas** [comment]
Het bleef op de oude versie, ik heb het nu opgelost, door packages.json te
veranderen van 1.11 naar 1.19. dat werkte. Bedankt voor jullie hulp!

Groeten, Ik.
