### ISSUE TITLE
Invalid_Grant bij firstrun

### ISSUE THREAD

**Issue by ghost** [lesander/magister-calendar#13]
Hallo,

Sinds kort doet het programma het bij mij niet meer. Ik heb alles verwijderd en probeerde hem opnieuw te installeren maar nu krijg ik een error bij firstrun.

`Testing calendar authorization.
The API returned an error: Error: invalid_grant`

Mvg, Bruce

**Comment by lesander** [comment]
Hallo Bruce,

De error `invalid_grant` kan door verschillende oorzaken voorkomen. Zorg er voor dat de bestanden in `~/.credentials/` en je `client_secret.json` geldig zijn, en je Google Account nog toegang geeft aan je Applicatie. Een snelle Google search geeft een hoop oorzaken om je eens in te verdiepen: http://lmgtfy.com/?q=Error%3A+invalid_grant+Google+calendar+api

Zou je de volledige output van `firstrun.js` kunnen delen? In principe hoef je firstrun maar één keer te draaien, tenzij je een nieuwe Google Applicatie wil verbinden met Magister Calendar. Wat geeft `magister-calendar.js` aan?

-- Sander

**Comment by lesander** [comment]
Is het probleem ondertussen opgelost @brucemartens?
