### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by poespas** [lesander/magister-calendar#15]
Als ik magister-calendar.js probeer te laden, krijg ik een foutmelding per les:

>  Error creating appointment. {"errors":[{"domain":"global","reason":"authError","message":"Invalid Credentials","locationType":"header","location":"Authorization"}],"code":401,"message":"Invalid Credentials"} 

Het heeft eerst gewerkt, volgensmij heeft dit te maken met Google

Groeten, Mij

**Comment by lesander** [comment]
Hey Wortel,

Zou je de hele output kunnen delen van magister-calendar.js? Weet je zeker dat je client_secret.json geldig is?

-- Sander

**Comment by poespas** [comment]
Beste Sander,

Ik ben nu op school, dus ik zal vanmiddag de hele output sturen. Ik heb
gisteren de client_secret.json opnieuw gedownload, maar dat hielp niet

Mvg, Wortel

**Comment by poespas** [comment]
Hier is de output:

http://pastebin.com/gq0Aauut

Groeten, Wortel.

**Comment by lesander** [comment]
Wortel,

Om je probleem op te lossen ga ik er van uit dat je zelf ook initatief toont om mee te denken, anders komen we niet ver.

Zoals je zelf al aan geeft heeft dit waarschijnlijk te maken met Google's OAuth. Zie Google's API [Handle API Errors](https://developers.google.com/google-apps/calendar/v3/errors#400_bad_request). Waarschijnlijk is er een probleem met het ophalen van de nieuwe Access Token.

```
{"errors":[{"domain":"global","reason":"authError","message":"Invalid Credentials","locationType":"header","location":"Authorization"}],"code":401,"message":"Invalid Credentials"}
```

Ik heb Magister Calendar aangepast waardoor errors met het ophalen van de OAuth Access Token nu ook weergegeven worden. Update Magister Calendar naar `v1.6.0` en kijk dan welke foutmelding je te zien krijgt.

-- Sander

**Comment by poespas** [comment]
Oke, dankjewel. Ik zal vanmiddag even kijken

**Comment by poespas** [comment]
Blijkbaar is er opeens niks aan de hand, wat je hebt gedaan weet ik niet,
maar dankjewel!

**Comment by lesander** [comment]
Vreemd, ik heb alleen een extra error handler toegevoegd (https://github.com/lesander/magister-calendar/commit/1405792f87ba54ff8ceecd4744deeb382f9e3822). Mooi dat het nu werkt!
