### ISSUE TITLE
Inloggen lukt maar daarna komen foutcodes waar ik geen verstand van heb.

### ISSUE THREAD

**Issue by hahadmin** [lesander/magister-calendar#16]
Hallo,

Ik ben compleet niet in deze wereld en ben bezig om dit voor mijn dochter op te zetten. Zij moet een betere planning maken voor zichzelf en toen dacht ik dat het handig is om de huiswerkafspraken automatisch in de Google Agenda binnen te laten komen en dat zij m.b.v. kleuren aan kan geven of iets maakwerk, leerwerk of een toets is. Het gaat helemaal goed tot het laatste gedeelte, het inlezen van de gegevens. Ook het inloggen in magister lukt. Zie hieronder het resultaat.

```
C:\Users\XXX\Documents\magister>node magister-calendar.js
[*] 12:35:42 Magister Calendar v1.5.1 started.
System Time: 12:35:42
[*] 12:35:42 Using default period to fetch appointments for.
[*] 12:35:42 Determined period is:
From Wed Jun 01 2016 12:35:42 GMT+0200 (West-Europa (zomertijd))
To Fri Jun 03 2016 12:35:42 GMT+0200 (West-Europa (zomertijd)).
[*] 12:35:42 Google OAuth2 token is valid.
C:\Users\XXX\Documents\magister\node_modules\magister.js\lib\node\magister-node.js:3441
            setSessionId(/[a-z\d-]+/.exec(r.headers["set-cookie"][0])[0]);
                                                                 ^

TypeError: Cannot read property '0' of undefined
    at C:\Users\xxx\Documents\magister\node_modules\magister.js\lib\node\magister-node.js:3441:66
    at Request._callback (C:\Users\xxx\Documents\magister\node_modules\magister.js\lib\node\magister-node.js:5381:16)
    at Request.self.callback (C:\Users\xxx\Documents\magister\node_modules\magister.js\node_modules\request\request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\xxx\Documents\magister\node_modules\magister.js\node_modules\request\request.js:1073:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\xxx\Documents\magister\node_modules\magister.js\node_modules\request\request.js:1019:12)
    at emitNone (events.js:72:20)
```

Aangezien ik niet in deze programmaeertaal thuis, zou ik het zeer op prijs stellen als iemand mij hiermee verder kan helpen.

Met vriendelijke groet en alvast bedankt,

Marco

**Comment by lesander** [comment]
Hallo Marco,

Is het al gelukt? Ik zie dat je de issue gesloten hebt. 
Graag hoor ik het als ik je kan helpen.

-- Sander

**Comment by hahadmin** [comment]
Hoi Sander, het is nog niet gelukt maar toen ik de mijn bericht wilde editten omdat er een foutje in stond werd er nog een lijntje aangemaakt. Nummer 17. Daarom heb ik nummer 16 gesloten. Het probleem is er dus nog steeds.

Groet,

Marco.

**Comment by lesander** [comment]
Marco,

Ik zie dat er een `TypeError` opkomt in de module **Magister.js** (van @lieuwex). Misschien komt dit door het feit dat je nodejs op Windows draait, of je niet de laatste versie van de module [`magister.js`](https://github.com/simplyGits/MagisterJS) hebt. 

Om dat laatste zeker te weten draai je in de `magister-calendar` folder:

```
npm list
```

Om te zien wat de versies zijn van de geïnstalleerde modules. De laatste versie van MagisterJS is momenteel `1.21.0`.

Om MagisterJS te updaten:

```
npm install magister.js --save
```

@lieuwex Verder weet ik niet wat het probleem kan zijn, zo te zien bestaat de header `set-cookie` niet in `magister-node.js @ 3441`. Windows issue of (oude) bug?

-- Sander

**Comment by lieuwex** [comment]
Ik kijk er vanmiddag naar!

**Comment by hahadmin** [comment]
Dag Sander,

Even voor de volledigheid. Ik werd onder Windows 10 32 bits. Ik heb de
nieuwste node gedownload. Die werkt dus niet met 'nodejs' in het commando
maar met 'node'. het opvragen van de lijst levert inderdaad versie 1.21.0
op maar ik heb hem voor de zekerheid toch maar even met het opgegeven
commando geüpdate. Helaas zonder resultaat. De laatste resultaten zijn
exact hetzelfde als bij mijn eerste melding.

Groet,

Marco

Op do 2 jun. 2016 om 12:39 schreef Lieuwe Rooijakkers <
notifications@github.com>:

**Comment by lieuwex** [comment]
Hoi Marco!

Als je onderstaande zip file uitpakt en de MagisterJS map in `node_modules` vervangt met onderstaande versie en magister-calendar opnieuw opstart zou het nu meer informatie moeten weergeven. Zou je dan weer de logs hier willen plaatsen?
http://tomsmeding.com:11056/vang/0z4cw5q (link 24u geldig)

Mvg,
Lieuwe

**Comment by hahadmin** [comment]
Dag Lieuwe,

Bedankt dat je mij ook wilt gaan helpen. De map die er nu in staat heet
'magister.js'. Jouw map het 'MagisterJS'. Maakt dat wat uit?

Groet,

Marco.

Op do 2 jun. 2016 om 16:59 schreef Lieuwe Rooijakkers <
notifications@github.com>:

**Comment by lieuwex** [comment]
Oh mijn fout! Verwijder de map 'magister.js', plaats de 'MagisterJS' map erin en hernoem het naar 'magister.js'. Dan zou het moeten werken

**Comment by hahadmin** [comment]
```
c:\Users\xxxxx\Documents\magister>node magister-calendar.js
[*] 17:37:50 Magister Calendar v1.5.1 started.
System Time: 17:37:50
[*] 17:37:50 Using default period to fetch appointments for.
[*] 17:37:50 Determined period is:
From Fri Jun 03 2016 17:37:50 GMT+0200 (West-Europa (zomertijd))
To Fri Jun 03 2016 17:37:50 GMT+0200 (West-Europa (zomertijd)).
[*] 17:37:50 Google OAuth2 token has expired. Requesting a new one.
[*] 17:37:51 Updated OAuth2 token.
deleteUrl https://beatrix.magister.net/#//api/sessies/huidige
postUrl https://beatrix.magister.net/#//api/sessies
==========
{"content":"<html><head><title>Object moved</title></head><body>\r\n<h2>Object moved to <a href=\"/404.html?aspxerrorpath=/\">here</a>.</h2>\r\n</body></html>\r\n","headers":{"cache-control":"no-cache","content-type":"text/html; charset=utf-8","location":"/404.html?aspxerrorpath=/","date":"Thu, 02 Jun 2016 15:37:49 GMT","connection":"close","content-length":"142","x-frame-options":"DENY","strict-transport-security":"max-age=31536000"},"statusCode":302}
c:\Users\xxxxx\Documents\magister\node_modules\magister.js\lib\node\magister-node.js:3448
            setSessionId(/[a-z\d-]+/.exec(r.headers["set-cookie"][0])[0]);
                                                                 ^

TypeError: Cannot read property '0' of undefined
    at c:\Users\xxxxxt\Documents\magister\node_modules\magister.js\lib\node\magister-node.js:3448:66
    at Request._callback (c:\Users\xxxxx\Documents\magister\node_modules\magister.js\lib\node\magister-node.js:5389:16)
    at Request.self.callback (c:\Users\xxxxx\Documents\magister\node_modules\magister.js\node_modules\request\request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (c:\Users\xxxxx\Documents\magister\node_modules\magister.js\node_modules\request\request.js:1073:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (c:\Users\xxxxx\Documents\magister\node_modules\magister.js\node_modules\request\request.js:1019:12)
    at emitNone (events.js:72:20)
```

**Comment by hahadmin** [comment]
Ik hoop dat je er wat aan hebt. Ik heb het idee dat de oplossing heel dichtbij is maar het is die bewuste speld in de hooiberg waarnaar je moet zoeken. Succes.

Marco

**Comment by lieuwex** [comment]
Hoi Marco, 

De URL klopt niet, er staat een '#' achter, 'magister_url' moet 'https://beatrix.magister.net' zijn.

@lesander misschien is het een nuttige toevoeging om de path van de url te negeren, zou dit denk je handiger zijn in magister.js of in magister-calendar?

**Comment by hahadmin** [comment]
Hoi Lieuwe,

Bravo, het komt nu wel binnen maar inderdaad alleen van morgen omdat het
morgen de laatste dag van de week is. Ik dacht dat door de default aan te
passen naar '14' hij het voor de komende twee weken zou doen maar dat doet
hij niet. Zie ik dan iets over het hoofd?

Ik vermoed dat jullie dit als hobby doen en niet als professionals ook al
zijn jullie wel heel professioneel bezig maar ik heb nog één andere vraag.
Kan je ook de kleur van de nieuw ingelezen afspraken een standaard
achtergrondkleur geven? Zodat je kan zien welke huiswerkopdrachten er nieuw
zijn en daar actie op kan ondernemen?

Top dat jullie meedenken.

Thanks, Marco

Op do 2 jun. 2016 om 18:08 schreef Lieuwe Rooijakkers <
notifications@github.com>:

**Comment by lesander** [comment]
@hahadmin Tof dat alles werkt! 

>  Ik dacht dat door de default aan te
> passen naar '14' hij het voor de komende twee weken zou doen maar dat doet
> hij niet.

Het is de bedoeling dat je voor de instelling `period` alleen getallen gebruikt, en geen strings: `"period": 14` in plaats van `"period": "14"`.

> Kan je ook de kleur van de nieuw ingelezen afspraken een standaard
> achtergrondkleur geven? Zodat je kan zien welke huiswerkopdrachten er nieuw
> zijn en daar actie op kan ondernemen?

Sinds versie `1.6.0` kan je met [Pushover](https://pushover.net/) notificaties ontvangen wanneer er lessen uit vallen, lokalen veranderen en huiswerk aangepast is door de leraar(es), maar hier moet ik nog een documentatie voor schrijven.

Wat bedoel je verder met huiswerkopdrachten? Ik sta open voor suggesties om Magister Calendar uit te breiden en nog fijner te maken in gebruik :smile: 

---

@lieuwex Het is natuurlijk Magister Calendar's fout dat er niet gecheckt wordt of de Magister url wel een correcte link is, maar misschien is het wel handig als MagisterJS zelf ook een check heeft ingebouwd voor verkeerd opgegeven urls. Top dat het opgelost is :+1: 

-- Sander

**Comment by lieuwex** [comment]
> maar misschien is het wel handig als MagisterJS zelf ook een check heeft ingebouwd voor verkeerd opgegeven urls. 

Ik kan eindelijk zeggen dat ik het nu geïmplementeerd heb voor Magister.js v2:
- URL sanitation is verbeterd in https://github.com/simplyGits/MagisterJS/commit/93f3fce9ba20a2126de5b7c03d66f40d84d48b06 (haalt nu de paths weg enzo)
- Error bij invalide URL: https://github.com/simplyGits/MagisterJS/commit/5847990d5c6776b75bd56270daba955a31b3aa5d
