### ISSUE TITLE
Deels foutmeldingen bij het inlezen van de afspraken.

### ISSUE THREAD

**Issue by hahadmin** [lesander/magister-calendar#18]
Ik dacht, laat ik maar een nieuw lijntje maken omdat het vorige probleem wel is opgelost maar nu komen er bij het binnenhalen van de afspraken 2 foutmeldingen meerdere malen voor, te weten:

```
[!] 7:17:39 5830438 Error creating appointment. {"errors":[{"domain":"usageLimits","reason":"rateLimitExceeded","message":"Rate Limit Exceeded"}],"code":403,"message":"Rate Limit Exceeded"}
```

en

```
[!] 7:17:42 5830444 Error creating appointment. {"errors":[{"domain":"global","reason":"backendError","message":"Backend Error"}],"code":503,"message":"Backend Error"}
```

Vraag, wat doet hij met de foutmeldingen? Komen ze wel deels in de Google Agenda terecht of niet?

Of willen jullie dat ik eerst 1.6.0 installeer?

Groeten,

Marco.

**Comment by lesander** [comment]
**503 Backend Error** betekent dat er iets fout is gegaan aan Google's kant. Soms is dit omdat Google het op dat moment te druk heeft met verwerken of een andere (onbekende) reden.

**403 Rate Limit Exceeded** betekent dat de applicatie te veel aanvragen naar Google stuurt in een korte tijd, dit kan te maken hebben met het vaak achter elkaar draaien van Magister Calendar. Ik zal kijken of ik in een nieuwe versie dit beter kan aanpakken.

Als Magister Calendar `Error creating appointment` aan geeft, betekent het dat de appointment niet is aangemaakt in de agenda.

Zijn dit sporadische foutmeldingen, of krijg je dit constant, ook met dezelfde afspraken (Afspraken ID's staan na de tijd in de logs: `[!] 7:17:39 **5830438**`)?

Het is wel handig om up-to-date te blijven met het project, ook omdat fouten in de code tussentijds worden opgelost. Vergeet niet bij het updaten een kopie van de `config.json` te maken, en later de instellingen over te zetten in de nieuwe `config.json`.

-- Sander

**Comment by lesander** [comment]
Met versie `v1.7.0` van Magister Calendar komen deze foutmeldingen als het goed is niet meer voor.

-- Sander
