### ISSUE TITLE
Nieuwe foutmelding bij inlezen (versie 1.7.0)

### ISSUE THREAD

**Issue by hahadmin** [lesander/magister-calendar#21]
Daar ben ik weer.
Bij versie 1.7.0, krijg ik nu de volgende foutmelding:

```
[*] 15:31:33 5830434 Appointment is in cache.
[*] 15:31:34 5830434 Appointment has changed.
[*] 15:31:34 5830435 Appointment is in cache.
[*] 15:31:34 5830435 Appointment has changed.
[*] 15:31:34 5830448 Appointment is in cache.
[*] 15:31:34 5830450 Appointment is in cache.
[*] 15:31:34 5830450 Appointment has changed.
[*] 15:31:34 5830437 Appointment is in cache.
[*] 15:31:34 5830437 Appointment has changed.
[*] 15:31:34 5830459 Appointment is in cache.
[*] 15:31:34 5830456 Appointment is in cache.
[*] 15:31:34 5830456 Appointment has changed.
[*] 15:31:34 5830462 Appointment is in cache.
[*] 15:31:34 5805568 Appointment is in cache.
[*] 15:31:34 5830432 Appointment is in cache.
[*] 15:31:34 5830452 Appointment is in cache.
[*] 15:31:34 5830441 Appointment is in cache.
[*] 15:31:34 5830454 Appointment is in cache.
[*] 15:31:34 5830454 Homework has changed.
c:\Users\***\Documents\magister\assets\tools.js:66
    if (config.enabled !== true) {
              ^

TypeError: Cannot read property 'enabled' of undefined
    at Object.module.exports.sendPushMessage (c:\Users\***\Documents\magister\assets\tools.js:66:15)
    at parseAppointments (c:\Users\***t\Documents\magister\magister-calendar.js:421:15)
    at c:\Users\Lizet\Documents\magister\magister-calendar.js:271:5
    at c:\Users\***\Documents\magister\node_modules\magister.js\lib\node\magister-node.js:2750:18
    at c:\Users\***\Documents\magister\node_modules\magister.js\lib\node\magister-node.js:2725:20
    at Request._callback (c:\Users\***\Documents\magister\node_modules\magister.js\lib\node\magister-node.js:5389:16)
    at Request.self.callback (c:\Users\***\Documents\magister\node_modules\magister.js\node_modules\request\request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (c:\Users\***\Documents\magister\node_modules\magister.js\node_modules\request\request.js:1073:14)
```

Kunnen jullie daar iets mee?
Tweede vraag. Alle items die daarvoor zijn ingelezen worden die wel verwerkt in de agenda of wordt er een bestand aangemaakt die na dit proces wordt ingelezen?

Groeten,

Marco.

**Comment by lesander** [comment]
Hi Marco,

```
[*] 15:31:34 5830454 Homework has changed.
c:\Users\***\Documents\magister\assets\tools.js:66
    if (config.enabled !== true) {
              ^

TypeError: Cannot read property 'enabled' of undefined
```

Dit komt waarschijnlijk omdat je de inhoud van je oude `config.json` in de nieuwe `config.json` hebt geplaatst. Nu kan Magister Calendar nieuwe belangrijke instellingen niet vinden omdat die in de oude configuratie nog niet bestonden.

Gebruik de [`config.json`](https://github.com/lesander/magister-calendar/blob/master/config.json) van v1.7.0 en vul die in met de gegevens van je oude configuratie.

---

Wat betreft je vraag: de workflow van Magister Calendar gaat als volgt:
1. Instellingen laden en toepassen.
2. Periode bepalen om van Magister te halen.
3. Google Authenticatie voorbereiden.
4. Magister afspraken binnen halen.
5. Afspraken inlezen en zo nodig update naar Google sturen.

Alle afspraken worden zodra het kan naar Google gestuurd, dus alle afspraken die voor de foutmelding zijn behandeld zijn ook naar je agenda gestuurd. 

Alleen is het script waarschijnlijk zo snel gecrasht dat Magister Calendar niet meer de kans kreeg om de aanvragen naar Google af te handelen. 

Als een afspraak is ontvangen door Google staat er in je log iets als

```
[*] 12:34:56 1234567 Updated appointment.
[*] 12:34:56 8901234 Created appointment.
```

Indien je nog vragen hebt of hulp nodig hebt hoor ik het graag!

Groeten,
Sander

**Comment by hahadmin** [comment]
Hoi Sander,

Klopt, ik was op het verkeerde been gezet doordat er was gezegd dat ik de oude config.json moest bewaren. Dat had ik dus gedaan en die in de plaats van de nieuwe gezet. Inmiddels heb ik het volgens de nieuwe structuur aangepast en alles updates worden nu geparsed alleen krijg ik toch nog een foutmelding namelijk:

```
[*] 19:32:55 5830454 Updated appointment.
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EPERM: operation not permitted, open 'c:\Users\xxx\Documents\magister\cache\appointment_5830454.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at Request._callback (c:\Users\Lizet\Documents\magister\magister-calendar.js:584:8)
    at Request.self.callback (c:\Users\xxx\Documents\magister\node_modules\request\request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (c:\Users\xxx\Documents\magister\node_modules\request\request.js:1082:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
```

Groetjes,

Marco

**Comment by lesander** [comment]
Hi Marco,

```
Error: EPERM: operation not permitted, open
'c:\Users\xxx\Documents\magister\cache\appointment_5830454.json'
```

Dit betekent dat Magister Calendar geen toestemming heeft om dat bestand op te slaan in de cache folder.

Je kan proberen om de cache folder te verwijderen, Magister Calendar zal vanzelf de folder opnieuw aan maken. Hopelijk lukt het dan wel. 

Als dat niet lukt moet je kijken of er aparte permissies gelden voor de folder. Magister Calendar heeft schrijf en lees toestemming nodig in alle folders van `/path/to/magister-calendar` of in jouw geval `c:\Users\xxx\Documents\magister\`.

Groeten,
Sander

**Comment by hahadmin** [comment]
Ok, cache folder verwijderd. Opnieuw gedraaid. Eerst uiteraard een hoop foutmelding van afspraken die er al in stonden. Daarna opnieuw gedraaid en toe ging het weer foutloos. Thnx.

Gr.

Marco

**Comment by hahadmin** [comment]
Hoi Sander,

Nog even één ding om het verhaal compleet te maken. Wanneer je de cache leegmaakt worden daarmee ook handmatige mutaties binnen de afspraken verwijderd. Mijn dochter had dus de kleuren van de afspraken aangepast, toetsen had ze rood gemaakt, leerwerk oranje, maakwerk blauw en geen huiswerk grijs. Verder komen alle nieuwe of gewijzigde magisterafspraken geel binnen. Door het verwijderen van de cache moet ze die kleuren opnieuw veranderen. enige voorzichtigheid hierin is dus aanbevolen. Is het de volgende keer niet verstandiger om alles de afspraak waardoor de foutmelding komt, te verwijderen in plaat van de hele map?

Gr. Marco.

Gr. Marco.
