### ISSUE TITLE
Calendar ID en verwijderde afspraken

### ISSUE THREAD

**Issue by ph00lt0** [lesander/magister-calendar#25]
Hoi Sander,
Gaaf stukje programmeer werk hier!
Ik heb wel een probleempje, ik heb namelijk de calender ID aangepast zodat ik de afspraken gescheiden kan houden. Alleen blijven ze in default staan. Daarom heb ik een aantal afspraken verwijderd om te checken of ze dan wel goed worden geplaatst, maar verwijderde afspraken keren blijkbaar ook niet terug. Heb jij een idee hoe ik dit kan fixen?

^
Marijn

**Comment by lesander** [comment]
Hey Marijn,

In de 'cache' folder staan alle appointments gecached. Verwijder de appointments uit die folder om ze opnieuw naar Google te sturen.

**Comment by marijnpool** [comment]
Tnx!

* [image: Marijn Pool Multimedia Design] <http://marijnpool.com>*

marijnpool.com
marijn@marijnpool.com
+31 6 33804528*
* Alleen na 4 uur
DISCLAIMER
Deze mail en eventuele bijlagen kan informatie bevatten die vertrouwelijk
is en is uitsluitend bestemd voor de vermelde geadresseerde(n). Indien u
deze mail abusievelijk heeft ontvangen, dan verzoek ik u vriendelijk mij
hiervan op de hoogte te stellen en deze mail te vernietigen. Gebruik van de
inhoud door derden is zonder mijn toestemming verboden en ik ben op geen
enkele manier aansprakelijk voor de gevolgen bij ongeoorloofd gebruik van
de inhoud van deze mail en of bijlage.

Al mijn mails worden gecontroleerd op virussen, echter kan ik geen garantie
geven dat deze mail en eventuele bijlagen geen virussen bevatten. Het
geïnstalleerd hebben van de meest recente versie van uw antivirussoftware
wordt dringend aanbevolen.

De Algemene Voorwaarden van Marijn Pool Multimedia Design zijn hier
<http://marijnpool.com/algemene-voorwaarden.pdf> te vinden.​

**Comment by ph00lt0** [comment]
Tnx! Ik had net fout gemaakt dus mn magister is nu gebanned door teveel pogingen nu ff wachten op de systeembeheerder... maar denk dat dat het zal doen.

**Comment by lesander** [comment]
@marijnpool Kan ik de issue sluiten?

**Comment by ph00lt0** [comment]
Zeker! Alles werkt naar behoren. Ik ga samen met het ICTbeheer zorgen voor een webapp zodat alle docenten en leerlingen dit kunnen gebruiken.

**Comment by lesander** [comment]
Hey Marijn,

Tof! Hou me op de hoogte. Voor mijn oude school heb ik een zelfde soort
applicatie gemaakt, die zorgt dat alle afspraken up-to-date in de Google
agendas van leerlingen staan.

**Comment by ph00lt0** [comment]
Ons plan is om het op de server van school te draaien. Maar heb jij al een dergelijke applicatie gemaakt? Is die ergens te vinden wellicht dat er wat van te leren valt.
