### ISSUE TITLE
It stopped working 2 days ago...

### ISSUE THREAD

**Issue by SuperTommetje** [lesander/magister-calendar#30]
I don't know if this is a problem with my school's network but since 2 days ago I get an error;

>  Could not login to magister. {"0":"I","1":"n","2":"v","3":"a","4":"l","5":"i","6":"d","7":" ","8":"A","9":"P","10":"I","11":" ","12":"k","13":"e","14":"y"}

What could I do to fix this?

**Comment by lesander** [comment]
Hi Tom,

Thank you for opening an issue. The problem lies with an update of the Magister API. @lieuwex is working on a fix. (See the following issue: https://github.com/simplyGits/MagisterJS/issues/68). 

Once a fix has been released, you should update the MagisterJS package.

**Comment by lieuwex** [comment]
Fixed! (1.23.3)
