### ISSUE TITLE
error on firstrun.js 

### ISSUE THREAD

**Issue by JBroeren** [lesander/magister-calendar#36]
when running the firstrun.js file with the client_secret.json file in the correct file directory I get this error:
```
Testing calendar authorization.
The API returned an error: Error: unauthorized_client
```
I redid the authorization for the webapp on the google devolerpsconsole multiple times. Tried changing names and authorized redirecting-url but all returns the same error. Also tried without the authorized redirecting-url but the error then returned is:
```
/etc/magister-calendar/firstrun.js:63
  var redirectUrl = credentials.web.redirect_uris[0];
                                                 ^

TypeError: Cannot read property '0' of undefined
    at authorize (/etc/magister-calendar/firstrun.js:63:50)
    at processClientSecrets (/etc/magister-calendar/firstrun.js:48:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```
I currently am running the magister-calendar client on a Ubuntu 16.04 server, all required software is installed, I previously ran the magister-calender client but found it running into other errors (before that it did really well, thx for that though) so decided to do a reinstall. Didn't seem to quite help after all...

I cannot provide the previous errors since I deleted the entire magister-calendar folder before doing a reinstall. also I couldn't find any documents in the cache folder, also after engaging debugging mode.

looking forward to a response.

contents of my config.json

```
{
  "debug": true,
  "calendar": "primary",
  "period": "default",
  "day_is_over_time": 16,
  "magister_url": "*************.magister.net",
  "magister_username": "***********",
  "magister_password": "***********",
  "pushover": {
    "enabled": false,
    "token": "",
    "user": "",
    "device": ""
  },
  "remove_cancelled_classes": true,
  "blacklist": ["beweginsonderwijs", "KWT"],
  "reminders": [
    { "method": "popup", "minutes": "5" }
  ]
}
```

**Comment by lesander** [comment]
Hi there. Thank you for opening an issue. It seems that you do not have any redirect uri’s set in your client_secret.json file. Please make sure you’ve added a redirect uri in the Google Cloud Console per the tutorial.

**Comment by JBroeren** [comment]
When using this uri: http://localhost/authcallback I get the first mentioned error. (Testing calendar...). I'm sorry for not being clear about that...

**Comment by jb2210** [comment]
![Google developers console](https://i.imgur.com/Gq3AtBY.jpg)

**Comment by JBroeren** [comment]
![](https://i.imgur.com/m4PFl6x.jpg)

**Comment by JBroeren** [comment]
My server is a, throught http and https, over the internet reachable server, not sure if that makes any difference?

**Comment by lesander** [comment]
I think you forgot to add a valid authorised JavaScript source. This should work:

```
Authorised JavaScript Sources:
http://localhost

Authorised Redirect URI's:
http://localhost/
```

**Comment by JBroeren** [comment]
okay I found a solution, it wasn't troubling at the developers console end. It was the .credentials file causing all the trouble. after deleting it, the program ran like a charm. again thanks for developing such a useful program.
