### ISSUE TITLE
KWT uren wegfilteren

### ISSUE THREAD

**Issue by yochem** [lesander/magister-calendar#37]
Hi sander,

Ik gebruik magister-calendar nu al een tijdje, en ben er erg blij mee :smile:. Merk echter al een tijdje dat de KWT (niet ingeplande lessen) alsnog in de agenda verschijnen. Naar mijn weten is dit iets dat werd voorkomen. Klopt dit? Of is dit uit de code gehaald? 

Ik ben op dit moment niet in staat om te kijken welke versie ik heb. Zal dat eind van de middag doen.

**Comment by lesander** [comment]
Hi Yochem,

Leuk om te weten dat dit nog gebruikt wordt 😁. In `config.json` wordt in de array `blacklist` aangegeven welke afspraak titels er genegeerd moet worden. Ik gok dat de standaard KWT titel dus iets veranderd is.

**Comment by yochem** [comment]
Denk dat ik nog een van de weinige ben op het pierson die het gebruikt😅 zal thuis even ernaar kijken
