### ISSUE TITLE
Error requesting new Google OAuth2 token

### ISSUE THREAD

**Issue by KimHernandez** [lesander/magister-calendar#38]
Hey,

Recently, I have problems loading the appointments to my google calendar. Someone else on the forum had the same question and I followed every step, but it did not work for me.

This is my crash log that returned after I typed `node magister-calendar.js` in my terminal.
[crash_1528729744087.log](https://github.com/lesander/magister-calendar/files/2090573/crash_1528729744087.log)

Do you have any idea how I could solve this problem?

**Comment by lesander** [comment]
Hi Sjoerd,

The following line tells you more about your crash:
```
[!] 17:9:4 Problem requesting new OAuth2 token:  {"error":"invalid_request","error_description":"Missing required parameter: refresh_token"}
```

Magister Calendar can not request an OAuth2 token without a refresh token in the `calendar-api.json` file in the `~/.credentials` folder. Please make sure you ran `firstrun.js` successfully at least once per the documentation.

**Comment by KimHernandez** [comment]
When I run `firstrun.js`it gives an error that says: `invalid_request`
But this all happened quite sudden, because the day before this happened, I had no problems at all.

**Comment by lesander** [comment]
Could you share the output of firstrun.js as well?

**Comment by KimHernandez** [comment]
This is the output I get:

<img width="570" alt="schermafbeelding 2018-06-12 om 17 02 48" src="https://user-images.githubusercontent.com/12530580/41299015-cbac2778-6e62-11e8-9fb6-d20de7f58990.png">

**Comment by lesander** [comment]
Are you sure your `client_secret.json` file is in the magister-calendar folder?

**Comment by KimHernandez** [comment]
Yes, I know for sure and I have tried to use a different API with the new client secret file, but it did not work either

**Comment by lesander** [comment]
When you download a `client_secret_1234-your-app-id.apps.googleusercontent.com.json` file from Google, make sure you actually rename the file to `client_secret.json` in the magister-calendar folder.

**Comment by KimHernandez** [comment]
Yes, that is what I did and I have tried it for like five times already

**Comment by lesander** [comment]
Well the reason it's not working is because `firstrun.js` is not able to collect a `refresh_token` from Google's Calendar API. Please make sure you've enabled the Google Calendar API in your Google Cloud Console and have followed all steps in the set-up guide.

**Comment by KimHernandez** [comment]
Well I think I did, but how can you see that?

**Comment by KimHernandez** [comment]
Hey, recently I tried to use the `client_secret.json` file from a different account, but that didn't work out either. So, I think I did someting wrong while creating the Google Calendar API, but I don't know what I did wrong, because I followed every step.

**Comment by lesander** [comment]
Hi Sjoerd, 

I hope you've found a fix for this issue. The problem here clearly was (or is) in the Google API setup. I'm sorry if I wasn't able to help you resolve your problem, I however can't help you with your Google API setup. Please take another look at the Google API setup tutorial as I previously commented.

I'm closing this issue now due to inactivity. If you ever encounter another problem, please don't hesitate to open a new issue.
