### ISSUE TITLE
Magister login werkt niet :-(

### ISSUE THREAD

**Issue by Th0masDB** [lesander/magister-calendar#44]
Hoi ....,
Ik krijg nu iedere keer de zelfde error. Zie hier beneden. En ik heb MagisterJS geupdate!
Kun je dit oplossen? Ik weet zelf daar niet genoeg JS voor. :-)
Alvast bedankt! Werkte normaal SUPER!
Log:
`[*] 16:37:7 Magister Calendar v1.8.3 started.
[*] System Time: 4:37:07 PM, date: Mon, 25 Mar 2019 15:37:07 GMT
[*] 16:37:7 Debugging has been disabled.
[*] 16:37:7 Using default period to fetch appointments for.
[*] 16:37:7 Determined period is:
From Tue Mar 26 2019 16:37:07 GMT+0100 (CET)
To Fri Mar 29 2019 16:37:07 GMT+0100 (CET).
[*] 16:37:7 Google OAuth2 token is valid.
[*] 16:37:7 Created cache folder.
[!] 16:37:7 Could not login to magister. {"message":"The requested resource does not support http method 'DELETE'."}`

**Comment by jvdoorn** [comment]
Hallo!

Werkt mijn [branch](https://github.com/argetan/magister-calendar/) wel voor je?

**Comment by Th0masDB** [comment]
Jaa, het werk! BEDANKT!!! :-) :+1: 
Super werk! Kan ik iets doneren?

**Comment by jvdoorn** [comment]
Ik voel me verplicht om te vermelden dat @lesander alle eer toebehoort. Ik heb enkel wat bugs gefixed. Ik weet niet waar of hoe je zou kunnen doneren aan hem.

Ik werk met plezier aan dit soort projecten en hoef er niks voor terug, maar als je erop staat kan je [mijn PayPal](paypal.me/julianvd) gebruiken (dit is alleen die van mij, niet van @lesander).
